"""You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1: Input: s = "abcd", t = "abcde", Output: "e"
Explanation: 'e' is the letter that was added.
Example 2: Input: s = "", t = "y", Output: "y"

Constraints: 0 <= s.length <= 1000, t.length == s.length + 1
s and t consist of lowercase English letters."""

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        sum1 = 0
        for char in s:
            sum1 += ord(char)
        
        sum2 = 0
        for char in t:
            sum2 += ord(char)

        sum = sum2 - sum1
        return chr(sum)

        #or
        #return chr(sum(ord(char) for char in t) - sum(ord(char) for char in s))

test = Solution()
output = test.findTheDifference(s = "a", t = "aa")
print(output)